#!/bin/bash
set -o errexit
set -o xtrace

mkdir build
cd build

git clone --single-branch --branch databus https://github.com/jupyterlab/jupyterlab.git
cd jupyterlab
git checkout 53fc5378366041ba93fc4631d14ae1c3a16f45d8
cd ..

git clone https://github.com/jupyterlab/jupyterlab-metadata-service.git
cd jupyterlab-metadata-service
git checkout ee4e8e5f1228d2f73e5c4e431492a510036a40f8
cd backend
pip install -e .
cd jupyterlab_metadata_service_server
npm install
cd ../../..

git clone https://github.com/jupyterlab/jupyterlab-commenting.git
cd jupyterlab-commenting
git checkout 58e11b321a7341ef73a388b4dbc6807b2874f194
cd ..

cd jupyterlab
pip install -e .
jlpm run add:sibling ../jupyterlab-metadata-service/frontend 
jlpm run add:sibling ../jupyterlab-commenting
jlpm build:dev
jupyter lab build --dev
cd ../..